#!/bin/sh

# needed for "Save and Apply" to restart dailyreboot
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dynapoint[-1]
	add ucitrack dailyreboot
	set ucitrack.@dailyreboot[-1].init="dailyreboot"
	commit dailyreboot
EOF

rm -f /tmp/luci-indexcache
exit 0
